### ISSUE TITLE
Фильтр с списке сохранённых решений работает?

### ISSUE THREAD

**Issue by GloomlySeth** [AlekseySmorshchok/decisionTree#17]
Пробую набирать буквы всё пропадает

![image](https://user-images.githubusercontent.com/18662965/65586936-adc0fe80-df8d-11e9-98cf-d83973461876.png)

**Comment by AlekseySmorshchok** [comment]
фильтрацию делать по названию или всем полям?

**Comment by AlekseySmorshchok** [comment]
сделал по всем

**Comment by GloomlySeth** [comment]
Что-то не так. Смотрю список:

![image](https://user-images.githubusercontent.com/18662965/66055104-b3928300-e53d-11e9-9836-9484dc031a0c.png)

  Набираю в поиске букву "V" (и большую и малую результат идентичен), - всё пропадает и дерева в списке не находит

![image](https://user-images.githubusercontent.com/18662965/66055167-ce64f780-e53d-11e9-962d-abeb0b87e459.png)

**Comment by AlekseySmorshchok** [comment]
попробуйте почистить кэш. в зависимости от браузер разные комбинации у yandex ctrl+shift+r. так же это можно через историю сделать
![image](https://user-images.githubusercontent.com/25616141/66104188-76bba000-e5c0-11e9-8877-52b76c6a7b88.png)

**Comment by AlekseySmorshchok** [comment]
у меня работает 
![image](https://user-images.githubusercontent.com/25616141/66104211-8804ac80-e5c0-11e9-8584-c6e7d4a771ef.png)

**Comment by GloomlySeth** [comment]
Работает. 

Давай в эту таблицу ещё сделаем колонку "Дата создания"
