### ISSUE TITLE
Улучшить окно изменения критериев и альтернатив

### ISSUE THREAD

**Issue by GloomlySeth** [AlekseySmorshchok/decisionTree#18]
![image](https://user-images.githubusercontent.com/18662965/65587829-2e342f00-df8f-11e9-9139-f298ace121e1.png)

**Comment by AlekseySmorshchok** [comment]
готово

**Comment by GloomlySeth** [comment]
Отвечаю на вопрос: "в плане дописать размерность?"

Допустим я написал критерий: "Трудозатраты"
А хочу сделать : "Трудозатраты, часы"

Чтоб не писать заново слово "Трудозатраты", хорошо бы, чтоб оно оставалось в формочке изменения критерия
