### ISSUE TITLE
Не работает редактирование критерия

### ISSUE THREAD

**Issue by GloomlySeth** [AlekseySmorshchok/decisionTree#19]
1)  из этого окна перехожу  по кнопке "добавить критерий" (хорошо бы её переименовать в "добавить/изменить критерий")

![image](https://user-images.githubusercontent.com/18662965/65588014-79e6d880-df8f-11e9-85ec-1a9d6c8aa7f8.png)

2) жму редактировать критерий.
3) прописываю новый притерий
4) никакой реакции

С альтернативами не проверял, тоже должно работать

**Comment by AlekseySmorshchok** [comment]
работает)
