### ISSUE TITLE
Добавить сообщение пользователю

### ISSUE THREAD

**Issue by GloomlySeth** [AlekseySmorshchok/decisionTree#20]
Пока пользователь не заполнить в этом окне все значения критериев не пускаем его на парные сравнения. Выводим сообщение: "Заполните значения критериев" и подсвечиваем красным незаполненные.

![image](https://user-images.githubusercontent.com/18662965/65588524-5a9c7b00-df90-11e9-82e4-b3737e286fa0.png)

**Comment by AlekseySmorshchok** [comment]
![image](https://user-images.githubusercontent.com/25616141/65669211-cee82480-e04b-11e9-8b04-8ea04475f4cf.png)

**Comment by AlekseySmorshchok** [comment]
или сделать сообщения по центру?

**Comment by GloomlySeth** [comment]
Лучше по центру - в этом месте не каждый пользователь замеит.
Но если долго, то фиг с ним и так сгодится

**Comment by AlekseySmorshchok** [comment]
3 секунды висит

**Comment by AlekseySmorshchok** [comment]
ошибка воспроизводится только на сервере. позже посмотрю

**Comment by GloomlySeth** [comment]
Я имел ввиду, если долго переделывать, чтоб по центру выскакивала
