### ISSUE TITLE
Открытие сохранённого дерева решений подровнять

### ISSUE THREAD

**Issue by GloomlySeth** [AlekseySmorshchok/decisionTree#21]
При выборе сохранённого дерева решений открывается это окно

![image](https://user-images.githubusercontent.com/18662965/65813993-dc84e200-e1e4-11e9-8004-c438050d5a5b.png)

 нужно дать возможность пользователю внести изменения в дерево решений и приступить к парным сравнениям. Либо сделать одну кнопку "Редактировать" либо сделать окно идентичное окну с заполнением значений критериев.

**Comment by AlekseySmorshchok** [comment]
может на эту страницу переход сделать?
![image](https://user-images.githubusercontent.com/25616141/66035975-d65c7180-e514-11e9-953c-b95baf1119f2.png)

**Comment by GloomlySeth** [comment]
Ты показываешь страницу с результатами расчёта, а если я сохранился до того как до неё дошёл? 

  Давай так.
  Если пользователь дошёл до расчёта значений, то на ту страницу, что ты привёл
  Если не дошёл, как я в двух последних созданных деревьях, то на эту
![image](https://user-images.githubusercontent.com/18662965/66056663-256bcc00-e540-11e9-9363-e1152f214ff8.png)
