### ISSUE TITLE
Доработка интерфейса страницы авторизации/регистрации

### ISSUE THREAD

**Issue by AlekseySmorshchok** [AlekseySmorshchok/decisionTree#7]
![image](https://user-images.githubusercontent.com/25616141/65020262-89ce3f00-d935-11e9-9777-6fdbc8eaae74.png)

**Comment by AlekseySmorshchok** [comment]
сделать отступы, тоже самое для формы авторизации
![image](https://user-images.githubusercontent.com/25616141/65020333-ad918500-d935-11e9-87be-aac069dfd0ce.png)

**Comment by AlekseySmorshchok** [comment]
вход в эти страницы через кнопку в правом верхнем углу. в проекте путь к ним src->app->decision->header->user-> sign-in/sign-up.

**Comment by AlekseySmorshchok** [comment]
при появлении скролла сделать, чтобы он как нить гармоничнее смотрелся))) можно отвязать footer. и чтобы не было белых участков
![image](https://user-images.githubusercontent.com/25616141/65020642-3e686080-d936-11e9-9d99-5e778d04ee08.png)

**Comment by AlekseySmorshchok** [comment]
до 20.09.2019 хватит времени?

**Comment by amickulich** [comment]
До 21 :)

**Comment by AlekseySmorshchok** [comment]
ок
